# Generated by Django 3.1.7 on 2021-05-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20210503_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='back_side',
            new_name='definition',
        ),
        migrations.RenameField(
            model_name='flashcard',
            old_name='front_side',
            new_name='word',
        ),
    ]
